#!/usr/bin/env python3

"""
Main script to run fiscalcrypt tool

.. moduleauthor:: Armand BENETEAU <armand.beneteau@iot.bzh>

*Date: 24/04/2021*

*License:*
    Copyright (C) 2021 Armand Bénéteau

    This file is part of the Fiscal Crypt project.

    GNU General Public License Usage
    This file may be used under the terms of the GNU General \
    Public license version 3. This license is as published by the Free Software \
    Foundation and appearing in the file LICENSE included in the packaging \
    of this file. Please review the following information to ensure the GNU \
    General Public License requirements will be met \
    https://www.gnu.org/licenses/gpl-3.0.html.
"""
import json
import sys
from datetime import datetime
from dateutil.parser import isoparse
from decimal import *

from fiscal_crypt.price_finder.coinbasepro_finder import CoinbaseProFinder
from fiscal_crypt.platforms.coinbase import CoinbaseInterface
from fiscal_crypt.fcrypt_logging import fcrypt_log

COINBASE_API_KEYS_FILE = "coinbase_keys.json"

if __name__ == "__main__":

    try:
        # Get the file containing the keys
        with open(COINBASE_API_KEYS_FILE) as keys_file:
            coinbase_keys = json.load(keys_file)

        if ("api_key" not in coinbase_keys) or ("api_secret" not in coinbase_keys):
            fcrypt_log.error("[CONFIG] Missing keys in configuration file")
            sys.exit(1)

        # Create coinbase interface
        coinbase = CoinbaseInterface(coinbase_keys["api_key"], coinbase_keys["api_secret"])

        value = coinbase.get_wallet_value_at("XLM", "EUR", isoparse("2020-02-14T00:30:00Z"))
        normal_value = value.normalize()

        # Round to two places
        TWOPLACES = Decimal(10) ** -2
        display_value = normal_value.quantize(TWOPLACES)

        print(f"VALUE {str(display_value)} €")

    except Exception as err:
        fcrypt_log.error("[Exception] The following exception occured while fiscalcrypt was running:", str(err))
        sys.exit(1)
